# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-10-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Identificador'),
        ),
    ]
